### ISSUE TITLE
Lazy load data

### ISSUE THREAD

**Issue by m-mohr** [Open-EO/openeo-hub#12]
Due to the high amount of data that is loaded and processed, the browser sometime freezes on older computers. We need lazy loading for the Hub! So for example the 419 datasets from the GEE back-end should only be loaded once the area is expanded, same applies for the processes etc.

**Comment by christophfriedrich** [comment]
I don't consider this a bug. If you have an older computer, things are a bit slower, that's normal.

But in general I agree that lazy loading would be a very big improvement. That will be the next thing I'll start working on.

In the meantime, we probably (I didn't specifically test it) gained a lot of performance from switching all those `v-show`s to `v-if`s (https://github.com/Open-EO/openeo-vue-components/commit/6e8a9611d4364858ba7287e76ada9b05faefeee6).

**Comment by christophfriedrich** [comment]
This reduces the initial request that populates the "Discovery" section from 694 KB to 33 KB :tipping_hand_man:

I think that's big enough of a saving for now -- lazy-loading each individual section or even when scrolling a certain collection/process into view would be a bit over-the-top.

Feel free to re-open if you see more need.

**Comment by m-mohr** [comment]
Great, I guess the process graphs are only loaded once required for the process graphs tab? Or is it handled by #20?

**Comment by christophfriedrich** [comment]
> I guess the process graphs are only loaded once required for the process graphs tab?

*Now* they are :wink:
