### ISSUE TITLE
Only show "This data was chached at..." when there's a problem

### ISSUE THREAD

**Issue by christophfriedrich** [Open-EO/openeo-hub#13]
Currently, the "This data was cached at..." information is output quite prominently:

> ![image](https://user-images.githubusercontent.com/17781682/54292509-9f416580-45ae-11e9-82ea-b4cef5024f8a.png)

And that although it's usually not *that* interesting.

We could remove it from the output for the standard case (the user will assume the data is up-to-date anyway) and only show it when e.g. the data is older than 12 hours or the last crawl failed. And then we should display it with a warning sign like :warning:

**Comment by m-mohr** [comment]
I'd actually just put a warning sign after the title of the back-end and put the description with the cache time in a tooltip.

**Comment by christophfriedrich** [comment]
> I'd actually just put a warning sign after the title of the back-end and put the description with the cache time in a tooltip.

I like the idea to have a warning sign after the title. I implemented that:

![grafik](https://user-images.githubusercontent.com/17781682/55008746-b71edd80-4fe1-11e9-9312-0e7d861da64d.png)

It shows when

- `unsuccessfulCrawls` is higher than or equal to `config.unsuccessfulCrawls.flagAfter`

and/or

- `retrieved` is more than `config.flagWhenOlderThanXHours` hours ago.

But I didn't delete the DataRetrievedNotice in general -- I think it's fair to tell users that the data they see is not live but cached. Since the backends are now collapsed by default, the text isn't *that* prominent anymore anyway. And on top of that I made it smaller and gray so that it is even less prominent.

@m-mohr What do you think?

**Comment by m-mohr** [comment]
This is much better than before. The only thing that bugs me is that we now have three places with very similar information. I'd merge the red and grey texts and only show it in case there is a problem. I'd expect from portals/search engines that data is not live but cached...

**Comment by christophfriedrich** [comment]
> I'd merge the red and grey texts and only show it in case there is a problem.

Oookay.

Done:

![grafik](https://user-images.githubusercontent.com/17781682/55248675-868dac80-524a-11e9-8238-bd918034b37a.png)

The warning texts are always "behind the fold" i.e. only shown when the backend/collection/process is expanded (which is still obvious enough as their presence is indicated by the warning sign next to the backend name). Whether they are shown is determined by the `flagWhenOlderThanXHours` and `unsuccessfulCrawls.flagAfter` config options.

**Comment by m-mohr** [comment]
Better, but why don't we put it into a single paragraph?

**Comment by christophfriedrich** [comment]
Because they are two different things that can happen independent of each other.

**Comment by m-mohr** [comment]
The first issue implies the other, so a single message should be enough. It could be expanded though, for example:

1. [If crawling failed]: The data was collected 4 days ago as the backend was recently unavailable.
2. [If the data is just outdated]: The data was collected 4 days ago as openEO Hub could not [rough reason].
3. Otherwise nothing.

**Comment by christophfriedrich** [comment]
I opened a new issue because "as openEO Hub could not [rough reason]" requires that the reason is known to the Hub itself.
