### ISSUE TITLE
Show less information by default on discover page

### ISSUE THREAD

**Issue by m-mohr** [Open-EO/openeo-hub#14]
The discover page shows quite a lot of data by default. It would be nice if the back-end itself is collapsible and only shows title, version number and description by default. It could also show some additional information in small badges, for example whether a free plan is available or not or the status of the cache symbol (see #13) ...

After expanding a back-end the supported functionality should be expanded by default (maybe even the header could be removed). 

---

Tracking of progress:
- [x] backend itself is collapsible
- [x] shows title and version number
- [ ] shows description
- [ ] shows badges
- [x] supported functionalities are extended by default
- [x] hide "Show in Web Editor" button when not expanded

**Comment by christophfriedrich** [comment]
I partly implemented your requests, see the tickbox list in your original post.

How do you like this?

![grafik](https://user-images.githubusercontent.com/17781682/54946659-e4638100-4f38-11e9-89f2-d0bbb93dea0f.png)

I assume with "description" you mean the `description` field that is new and mandatory in v0.4 of the API? That depends on #17.

I didn't do any badges yet (who is the badge man? :thinking: :eyes: :new_moon_with_face: :wink:)

**Comment by m-mohr** [comment]
I like that. I think we could also remove the lines between the entries and only show the "Open in Web Editor" button once a back-end is expanded. I guess you'll only open it in web editor once you have looked at details and it makes things cleaner.

We can add the badges later, but I guess it's a good idea to have them for a quick overview (e.g. free/paid, API version, important functionalities such as UDFs, ...)

> I assume with "description" you mean the description field that is new and mandatory in v0.4 of the API? 

Yes.

**Comment by christophfriedrich** [comment]
> I think we could also remove the lines between the entries

To be honest I quite like them, especially when we'll have the description soon:
![grafik](https://user-images.githubusercontent.com/17781682/55245748-0d8b5680-5244-11e9-8679-1064ff1e630e.png)

>  and only show the "Open in Web Editor" button once a back-end is expanded.

That's a good idea, I implemented that.

**Comment by m-mohr** [comment]
Mostly done, open tasks are available in other issues.
