### ISSUE TITLE
There are two constants that map endpoints to functionalities

### ISSUE THREAD

**Issue by christophfriedrich** [Open-EO/openeo-hub#15]
Both the EndpointChooser and the SupportedFeatures component have to map endpoints to functionalities. For this I defined a single constant in the Hub that was used by both components. But since the SupportedFeature displaying was moved to the `vue-components` repo, there are two constants: one in each repo.

This isn't good as it's only a matter of time until one is updated and the other forgotten. There should be a "single source of truth".

I think the constant should be moved to the `js-commons` repo from where both the `vue-components` and `hub` repos can import it.

**Comment by m-mohr** [comment]
I agree, therefore https://github.com/Open-EO/openeo-vue-components/issues/5 was implemented and released as v0.3.2. The hub still needs to integrate it.
