### ISSUE TITLE
Searching for functionalities in different openEO API versions

### ISSUE THREAD

**Issue by christophfriedrich** [Open-EO/openeo-hub#19]
At the moment, the Hub just takes the `features` property from the `js-commons` repo's `FeatureList`:

https://github.com/Open-EO/openeo-hub/blob/f2076fde1ffcd4deb511b671eddda2306d4700e7/src/components/BackendSearch.vue#L42

https://github.com/Open-EO/openeo-hub/blob/f2076fde1ffcd4deb511b671eddda2306d4700e7/src/components/BackendSearch.vue#L52

This is probably problematic when dealing with different versions of the openEO API (i.e. v0.3.x and v0.4 backends).

**Comment by m-mohr** [comment]
Yes, the intended way of using it is getListForVersion(version) and/or getFeatures() depending on the use case.

**Comment by christophfriedrich** [comment]
Currently NO backend matches the 'Basic functionalities' filter because
1. that filter mandates `/file_formats` which is new in API v1.0, but no backend except GEE supports v1.0
2. that filter mandates `/credentials/oidc`, but GEE doesn't support it.

Not very nice behaviour, hence moving back to v0.5 milestone

**Comment by christophfriedrich** [comment]
The incompatibilities mentioned a few hours ago were fixed.

Current behaviour: The `EndpointChooser` always offers the functionalities of the latest API spec as returned by the `FeatureList`. When filtering the backends, old versions are converted to the latest spec for the comparison.

The proposed `getListForVersion` function does not exist anymore. And `getFeatures` has been moved to the `SupportedFeatures` component which doesn't make sense to use in this context. Therefore I don't regard the two lines of code I mentioned in the original issue as problematic anymore.

Except if we need a feature "Filter for _exactly this_ functionality that is no longer present in the latest spec".

But I think at least for now it's okay as it is, hence closing. Comment/reopen if you think otherwise.
