### ISSUE TITLE
Help user to select things (e.g. list or autocomplete)

### ISSUE THREAD

**Issue by christophfriedrich** [Open-EO/openeo-hub#25]
Currently the user can search for the names/identifiers of collections, processes, process parameters, output formats, and service types. These names are specified by typing them into a textfield, without any aid:

> ![grafik](https://user-images.githubusercontent.com/17781682/55804531-c3746180-5adc-11e9-90c3-d61735977b26.png)

This is not very user-friendly -- there should be a feature to assist with this. Typically this would be an autocomplete feature that suggests terms as the user types. Alternatively, for output formats and service types (and processes?) it may be an option to let the user choose the values from a simple list of all possible items.

*The "each in a new line" thing isn't very user-friendly either -- changing this into something better is tracked in #24.*

**Comment by christophfriedrich** [comment]
The new Filter feature supports auto-complete for collections, processes, output formats, and service types; i.e. this feature is now implemented for 4 out of the 5 inputs mentioned in the original issue. The only one missing is the one for the process parameters, but that's because they're being dropped from the feature altogether. Thus this issue can be closed.

**Comment by m-mohr** [comment]
Good work 👍
