### ISSUE TITLE
Various minor issues (0.4 compatibility?)

### ISSUE THREAD

**Issue by m-mohr** [Open-EO/openeo-hub#26]
- [x] 1. GEE v0.3.1 (and probably all other 0.3 back-ends) don't show "Preview processing results" as supported although it is (could potentially be an issue with vue-components).
- [x] 2. GEE v0.4.2 doesn't have output formats although available.
- [x] 3. "Open in openEO Web Editor" doesn't work for v0.3, only v0.4 is supported at editor.openeo.org. We need to discuss a solution for this.

**Comment by m-mohr** [comment]
> 1. GEE v0.3.1 (and probably all other 0.3 back-ends) don't show "Preview processing results" as supported although it is (could potentially be an issue with vue-components).

It doesn't seem to be an issue in vue-components, but in Backend.vue of the Hub. You don't pass the version to the vue-components, e.g. `<SupportedFeatures :endpoints="preparedBackend.endpoints" ref="supportedFeaturesComponent"></SupportedFeatures>` should be `<SupportedFeatures :endpoints="preparedBackend.endpoints" :version="preparedBackend.version" ref="supportedFeaturesComponent"></SupportedFeatures>`. This also applies to most (all?) other Vue components (Collection, Process, SupportedServiceTypes, BillingPlans, SupportedFileFormats, ...).

**Comment by christophfriedrich** [comment]
1. fixed
2. fixed on Hub side, waiting for OpenEO/openeo-vue-components#10, tracked in #31
3. Should we then simply remove the button for v0.3.x backends?

**Comment by m-mohr** [comment]
> 2. fixed on Hub side, waiting for [Open-EO/openeo-vue-components#10](https://github.com/Open-EO/openeo-vue-components/issues/10), tracked in #31

Fix is available.

> 3. Should we then simply remove the button for v0.3.x backends?

Yes.

**Comment by christophfriedrich** [comment]
> Fix is available.

Cool! Implemented in b3a2a1b -> closed #31.

> Yes, that's the easiest solution for now.

Thinking about it, I found disabling the button the nicer solution. This way we can display an explanatory tooltip via the `title` attribute :arrow_right: the user doesn't wonder why the button is sometimes there and sometimes not. I implemented it this way in 269d267.
