### ISSUE TITLE
Add information in UI: How to submit a new backend for indexing

### ISSUE THREAD

**Issue by m-mohr** [Open-EO/openeo-hub#27]
Transfered from #1:
Back-end providers should be allowed to add their back-ends using an UI

**Comment by christophfriedrich** [comment]
Is this _really_ necessary? I mean, how often does a new backend arise that needs to be integrated? My impression is that this is rare and can just as good be handled by email communication/coding a form for this and handling its submission introduces significant bureaucracy overhead.

**Comment by m-mohr** [comment]
We can surely go the PR approach. People can just do a PR against the config file.
So maybe just add a note to the About(?) page that describes how to add a new back-end.

**Comment by christophfriedrich** [comment]
Great idea! :+1:

**Comment by m-mohr** [comment]
For now, just add a paragraph to the About page. That should be easy enough.
