### ISSUE TITLE
Promote free back-ends

### ISSUE THREAD

**Issue by m-mohr** [Open-EO/openeo-hub#30]
Make free back-ends better visible by moving/copying the badge behind the back-end title.

**Comment by christophfriedrich** [comment]
_(aka the "show badges" part of #14)_

**Comment by m-mohr** [comment]
If one would be more sceptical, this issue could probably also be named "Promote GEE" in the long run. I'm not sure what other back-ends really have a free plan?! Maybe it's not worth implementing this?

**Comment by m-mohr** [comment]
Yes, came to the conclusion we don't want this at the moment.
