### ISSUE TITLE
Provide documentation for the backend's API

### ISSUE THREAD

**Issue by christophfriedrich** [Open-EO/openeo-hub#33]
At minimum for `GET /backends` so Solenix can use the list of available backends in their app

**Comment by m-mohr** [comment]
Maybe provide a "simpler" API (as OpenAPI document), which is stable and only returns a very limited set of information?!

**Comment by christophfriedrich** [comment]
What do you mean with "simpler"? It doesn't get much simpler than that: http://hub.openeo.org/backends

**Comment by christophfriedrich** [comment]
For now I only added text to the Readme -- this way it's easier to 1. explain the `details` parameter of the `/api/backends` endpoint and 2. say that `/api/process_graphs` works just like the openEO API itself.

Once the searching/filtering is refactored, we can think about making that part of the API public too, and *then* an OpenAPI document would indeed be handy.
