### ISSUE TITLE
Ordering of items in auto-complete suggestions appears random

### ISSUE THREAD

**Issue by christophfriedrich** [Open-EO/openeo-hub#38]
As far as I remember they are being ordered by count of occurences in the database (so that e.g. more common file formats appear on the top of the list), but this may not make sense for all inputs (e.g. there is usually only 1 collection with a certain name) and it may appear random to the user (even if GTiff is the most common one, they may expect ADRG to show up first just because it starts with an A).

This should be thought about and possible reworked.

**Comment by christophfriedrich** [comment]
Is the new ordering nice?

Specifically: Is sorting by count meaningful for collections? At the moment, each collection appears either once or twice in the database (depending on whether that backend is listed with one or two versions). This means that the suggestions are the concatenation of two alphabetically ordered lists.

For processes it's exactly the right approach IMO.

For file formats and service types I think that the current approach is okay, but I haven't dropped the idea of a simple A-Z ordering yet.

**Comment by christophfriedrich** [comment]
Discussed with Matthias:
- Displaying the count in brackets would explain ordering to the user
- Ordering by count is useful when opening component, but as soon as the user types, A-Z is more convenient
- Ordering by count is not really meaningful for collections
- Idea: Sort A-Z but display count anyway (I don't really like it)

(was that all?)

**Comment by m-mohr** [comment]
Revisit later whether it makes sense to implement ordering by count only when opening the component.

**Comment by christophfriedrich** [comment]
Implemented two of the four bullet points above. With those features the order no longer appears random, so I consider this issue fixed.

I opened another issue (#44) to track the "only order by count when opening" idea.
