### ISSUE TITLE
Style menu bar like the one at openeo.org (corporate design)

### ISSUE THREAD

**Issue by christophfriedrich** [Open-EO/openeo-hub#40]
Would look nicer when integrated into the new openeo.org website

**Comment by christophfriedrich** [comment]
openeo.org uses Roboto* as its font, the Hub so far just asks for the system's default `sans-serif`. Should this be harmonised too?

\* at least on my system that is what is chosen -- another check reveals that the actual `font-family` rule is: `-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,Oxygen,Ubuntu,Cantarell,Fira Sans,Droid Sans,Helvetica Neue,sans-serif` -- holy moly...

**Comment by m-mohr** [comment]
Well, that somehow makes sense although the list seems extensive. They seem to want to stick to system default fonts:
- -apple-system,BlinkMacSystemFont seems to be for Apple
- Segoe UI is Windows
- Roboto,Oxygen,Ubuntu,Cantarell,Fira Sans I think is for several *nix derivates
- Droid Sans sounds like Android
- not sure about Helvetica Neue
- and then default to the browser default sans-serif font

So yes, I think just copy that font-family declaration, too. ;-)

**Comment by christophfriedrich** [comment]
How do you like this?

![image](https://user-images.githubusercontent.com/17781682/84910580-56ccfd80-b0b7-11ea-805d-f6547b7c4bf0.png)

For comparison the openeo.org header:

![image](https://user-images.githubusercontent.com/17781682/84910546-49b00e80-b0b7-11ea-97db-c137f3c3f6b2.png)

**Comment by m-mohr** [comment]
Looks good, to be fully aligned the menu should be aligned to the right and the font-size should be smaller.

**Comment by christophfriedrich** [comment]
Aligning the whole menu to the right looks weird IMO:

![image](https://user-images.githubusercontent.com/17781682/84912115-559cd000-b0b9-11ea-8ebf-0b133085aa5d.png)

font-size smaller: okay, yeah that's better

Moving the text was well spotted: a vertical-align was missing.

I like this now:

![image](https://user-images.githubusercontent.com/17781682/84916068-e1186000-b0bd-11ea-8240-d8dd78c2af62.png)

**Comment by m-mohr** [comment]
Doesn't look weird to me, except for the extra spacing between openeo.org and the other items.

**Comment by m-mohr** [comment]
The text and especially the "external link" look darker than on openEO. Is that a thing or is it just a wrong impression on my side?

**Comment by christophfriedrich** [comment]
Maybe I think it's weird because those buttons used to be in the middle for the last 1.5 years. But on top of that, when on the far right and in smaller font-size, they are not prominent enough IMO: When the Exchange section comes back, the buttons to switch between the two modes should be immediately eye-catching (somehow the Hub is not like a normal website where you look for a menu anyway).

Wow, eagle's eyes! For the text it was font-weight 500 vs. bold (which equals 600).

The external link icon was missing `color: #aaa`, thanks

**Comment by christophfriedrich** [comment]
> And to back my point of aligning right: Wasn't this issue to align with openeo.org? ;-)

I must admit that this is a killer point :wink: And I will adhere to it if you want me to :innocent: 
But I thought of this issue more like "in the design of", not necessarily "copy every detail". Especially not if something else makes more sense for the Hub's case (read on to get what I mean with that)

> I don't understand this argument. Can you explain it?

With greatest pleasure ;)

For the Hub, if you don't know anything about it, it is quite reasonable to assume that what you see on the current start page is everything the page has to offer. While for a website, you know that there are most usually more subpages.

*Use case:*
Imagine Exchange was back, but Discover is still the front page. The menu items are small, subtly greyed, less-than-bold, at the far right. But the Discover section (and thus the start page) has many rather prominent UI elements like right now.
Now a user comes across the Hub and doesn't know anything about it, especially not that there is more than the Discover section. The probability that he will oversee that little change thingy in the very corner of his big screen (that is full with other things) will be high, and thus he may miss out on the Exchange section, which could've been avoided.

With your vision for a real start page, this issue is mostly mitigated though, true. But I didn't know about this vision yet, which is why I insisted on my proposal so much :ok_man:

**Comment by m-mohr** [comment]
Thanks for clarifying. I understand your point and agree with it (although I think the free floating navigation is not the best solution). It's true that there is no issue on the "vision" (e.g. front page) and I opened one now: #73 

You are correct: "it is quite reasonable to assume that what you see on the current start page is everything the page has to offer." So the menu can be right aligned at the moment as you are not missing anything substantial, right? ;-)

**Comment by christophfriedrich** [comment]
> So the menu can be right aligned at the moment as you are not missing anything substantial, right? ;-)

Oh well, it looks like my arguing cat bit its own tail haha :D

thx for the separate issue
