### ISSUE TITLE
Remove Search section

### ISSUE THREAD

**Issue by christophfriedrich** [Open-EO/openeo-hub#42]
Most things that can be done there are now also available in the Discover section via the (nicer) filtering feature.

After the last two big things (searching for collections by spatial/temporal extent, searching for backends by submitting a process graph) are moved there too, the Search section can be removed altogether.

**Comment by christophfriedrich** [comment]
This will automatically resolve #16, #21

**Comment by christophfriedrich** [comment]
The `remove-search-section` branch now contains a version of the Hub without the Search section. It still needs to be merged into master (which I will do after examining in all peace and quiet that I _really_ didn't break anything) but essentially this issue can be closed (and thus the other two that it automatically resolves, and thus the v0.4 milestone). Guten Rutsch! :fireworks:

**Comment by m-mohr** [comment]
Nice!
Frohes neues Jahr :-)

**Comment by christophfriedrich** [comment]
Merged. :heavy_check_mark:
