### ISSUE TITLE
Re-implement searching for backends by process graph

### ISSUE THREAD

**Issue by christophfriedrich** [Open-EO/openeo-hub#46]
This is a big one. So far this was only possible for the old openEO API v0.3 process graphs. But with v0.4 of the API the structure of process graphs changed enormously, so a major overhaul of this feature is needed.

This feature already existed, but was lost when removing the Search section (#42). That wasn't that bad because as mentioned, the feature was outdated anyway. But this feature is *very* useful, so it should definitely be re-implemented into the Filtering feature of the Discover section.

**Comment by m-mohr** [comment]
I'm not sure whether it's really that big. Using the process graph parser in JS commons you get most things "for free". I'm doing similar things already in the Web Editor so I can assist later this year if needed.

**Comment by christophfriedrich** [comment]
It now works! Providers are being removed from the list if _none_ of their backends can be validated positively with the validator from `openeo-js-processgraphs` (which checks processes and their schemata). The availability of the specified collections is not taken into account yet.

**Comment by christophfriedrich** [comment]
Considering that collections can look vastly different across backends even if they come from the same satellite: Should checking for them be a required part of this feature or can it be considered complete as it is now? I'm not entirely up to date concerning ideas within openEO that could mitigate this problem, like canonical aliases or process graph variables.

**Comment by m-mohr** [comment]
Can be closed for now, I think. Filtering by ID is indeed not the most useful thing...
