### ISSUE TITLE
Minor cosmetic improvement for filter section

### ISSUE THREAD

**Issue by m-mohr** [Open-EO/openeo-hub#50]
The functionalities box is scrollable although there's some space left on some screens.
I'd propose to change the HTML/CSS a bit to support flex box stretching:

1. Put The checkboxes/labels for "openEO API versions" and "Billing" in a div so that it doesn't show multiple lines once flex box is active on the parent.
2. Change CSS at `section#discover-filters`: `display: flex; flex-direction: column`
3. For `.endpointchooser.compact` replace `max-height: 5em;` with `max-height: fit-content; min-height: 3em; flex: 1`.

**Comment by christophfriedrich** [comment]
Mainly agreed.

On screens with a lot of available height, using `flex: 1` results in _this_:

> ![grafik](https://user-images.githubusercontent.com/17781682/72166077-e237b980-33c8-11ea-9888-04aa89027667.png)

But that can be fixed by using `flex-shrink: 1` instead.

And you don't really need `max-height: fit-content`, do you? (BTW it's `-moz-fit-content` in Firefox, i.e. still experimental :confused:)

**Comment by christophfriedrich** [comment]
Seems like the `fit-content` part didn't do anything in my Firefox (because it's experimental?), but relieved the too-big-box in your Chrome.

But `flex-shrink` works in both, so we shall use that.
