### ISSUE TITLE
Remove back-end from Hub when not available in well-known discovery

### ISSUE THREAD

**Issue by m-mohr** [Open-EO/openeo-hub#52]
Based on discussions in #49: Now that we have the well-known discovery document, back-end versions should reflect that document and get removed once it is not listed there any longer. This will remove the behavior that back-ends are only removed after a certain number of days with unsuccessful crawls (`unsuccessfulCrawls.deleteAfter`).

**Comment by christophfriedrich** [comment]
I now implemented that, however it was not as trivial as I thought initially. When tolerating temporary unavailability, a few more things have to be considered -- see my extended commit message.

Note especially that this will NOT remove the unsuccessfulCrawls behaviour altogether.

---

I just noticed that I should make one more addition to that commit message:
> What happens if a service is removed from the `config.json`? Its backends will be removed from the database during the next crawl, because they can neither show up in allIndividualBackends (because their service's well-known doc [from where they would need to be referenced] will no longer be attempted to be crawled anyway) nor in allFailedServices (because when there's no attempt there can't be a fail either).
