### ISSUE TITLE
Supported versions in crawling and discovery (drop 0.3, add 1.0)

### ISSUE THREAD

**Issue by m-mohr** [Open-EO/openeo-hub#53]
1. Drop support for API version 0.3
2. Add support for API version 1.0

**Comment by m-mohr** [comment]
I just realized that 1.0 support also includes to update the process graph exchange section and its API. New name for process graphs: User-defined processes

**Comment by christophfriedrich** [comment]
Thanks for the hint, I'll track that in a separate issue.

**Comment by christophfriedrich** [comment]
Is there anything else that is needed to make this issue complete? Going through the API v1.0 changelog I saw that I already implemented the biggest things (see above), lots of stuff is already taken care of by the vue-components (e.g. deprecated collections), many things are not related to discovery (e.g. everything job) or not interesting for Hub users (e.g. `/conformance`).

What I spotted as still implementable:

1. new `production` field in `/` (I think `stac_version` and `id` are not interesting)
2. :hourglass_flowing_sand:

**Comment by m-mohr** [comment]
Not sure what the current status of implementation is, but if it's working in general and is (mostly) on par with the "0.4 Hub" then I'd think it could be considered finished. We can track other issues separately.

**Comment by christophfriedrich** [comment]
It _is_ working in general and can be seen as equivalent to what was possible before -> agreed

So as a last thing I now implemented the `production` field and then **this shall be considered finished**. If something more comes up -> new issue.
