### ISSUE TITLE
Use map from vue-components?

### ISSUE THREAD

**Issue by m-mohr** [Open-EO/openeo-hub#54]
The Collection component in vue-components shows now a map if leaflet is available.
Please check whether you can use the default map instead of drawing your own map. :-)

**Comment by christophfriedrich** [comment]
How does this work? I tried specifying no `collection-spatial-extent` at all, or an empty one, but none of these tries resulted in a map being rendered. Leaflet _should_ be available.

**Comment by m-mohr** [comment]
Fixed with commit a4818992b985a80624bd6b430f26175eb82a36e5
