### ISSUE TITLE
Show links

### ISSUE THREAD

**Issue by christophfriedrich** [Open-EO/openeo-hub#64]
I just realised that the links from the `/` response are not displayed in the Hub. I think they can provide useful information for someone who wants to know more about a certain backend, so they should be rendered. I guess the `LinkList` component could be used for that. It could be placed either after the description or in a separate collapse area (e.g. after Billing Information).

**Comment by m-mohr** [comment]
After the description sounds good. Make sure to only show meaningful links (i.e. rel type self is not so useful for example).

You can use the Vue Components LinkList for rendering. It automatically removes `self`. I'd propose to also ignore the following rel types (via the components `ignoreRel` prop): 
* `version-history` (already available in the hub)
* `conformance` (OGC conformance classes are just not very interesting to non-implementers)
* `data` (collections already available in the hub)
