### ISSUE TITLE
Disable exchange section for now

### ISSUE THREAD

**Issue by m-mohr** [Open-EO/openeo-hub#66]
The exchange section is not 1.0 compatible at all and needs a rework. People except it to work (#65), but the resources to make it work are limited. So the Exchange section should be disabled for now until we have time to actually update it and make it actually usable. The Web Editor already had to remove support, too, because compatibility was broken.

**Comment by m-mohr** [comment]
I reorganized the milestones a bit and we'll focus work on the Exchange part in v0.7

**Comment by christophfriedrich** [comment]
Agreed.
