### ISSUE TITLE
Adapt EndpointChooser to changed FeatureList.json

### ISSUE THREAD

**Issue by christophfriedrich** [Open-EO/openeo-hub#72]
Upstream change in vue-components: What were formerly arrays are now objects. See Open-EO/openeo-vue-components#23 for details.

**Comment by christophfriedrich** [comment]
The milestone depends on when the upstream change will be released

**Comment by m-mohr** [comment]
Released with 1.0.0-beta.6

**Comment by m-mohr** [comment]
Can this be closed?

**Comment by christophfriedrich** [comment]
Yes, this was the issue that was supposed to track the change that caused #77...
