### ISSUE TITLE
Search for Functionalities broken

### ISSUE THREAD

**Issue by m-mohr** [Open-EO/openeo-hub#77]
Similarly to #76, the Functionalities Chooser doesn't have any effect. Clicking e.g. UDFs doesn't change the list although GEE for example has no UDFs.

**Comment by christophfriedrich** [comment]
That was an error due to an upstream change (Open-EO/openeo-vue-components@594dd73) -- fixed now. As we did with the other bug, feel free to deploy the `development` branch to fix it on the deployed site.
