### ISSUE TITLE
Collection descriptions are empty everywhere

### ISSUE THREAD

**Issue by jdries** [Open-EO/openeo-hub#87]
When looking at collections in the hub, descriptions are no longer shown, even though they are available in the JSON.
![image](https://user-images.githubusercontent.com/5937096/106249737-07d17400-6213-11eb-9b7a-ab8946b62bf6.png)

JSON:
https://openeo.vito.be/openeo/1.0/collections/PROBAV_L3_S10_TOC_NDVI_333M

**Comment by m-mohr** [comment]
Yes, all comments are missing. It seems to be an upstream breaking change in the commonmark parser.

**Comment by m-mohr** [comment]
Descriptions should be back in!

**Comment by christophfriedrich** [comment]
Thanks for the hint, Jeroen!

How did you fix it, Matthias?

**Comment by m-mohr** [comment]
`npm install commonmark@0.29.1` - I know this version worked before. 0.29.2 was broken. 0.29.3 may fix it, too, but I've not tested it yet.
