### ISSUE TITLE
Dependency issue on Ubuntu?

### ISSUE THREAD

**Issue by m-mohr** [Open-EO/openeo-hub#88]
I'm getting the following error when running `npm install` on our Ubuntu 20 server:

npm ERR! code EBADPLATFORM
npm ERR! notsup Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin"} (current: {"os":"linux","arch":"x64"})
npm ERR! notsup Valid OS:    darwin
npm ERR! notsup Valid Arch:  undefined
npm ERR! notsup Actual OS:   linux
npm ERR! notsup Actual Arch: x64

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/m_mohr08/.npm/_logs/2021-07-23T10_16_06_817Z-debug.log
npm ERR! code EBADPLATFORM
npm ERR! notsup Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin"} (current: {"os":"linux","arch":"x64"})
npm ERR! notsup Valid OS:    darwin
npm ERR! notsup Valid Arch:  undefined
npm ERR! notsup Actual OS:   linux
npm ERR! notsup Actual Arch: x64

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/m_mohr08/.npm/_logs/2021-07-23T10_16_12_900Z-debug.log

**Comment by christophfriedrich** [comment]
I'm using Ubuntu 20 myself on my development laptop (20.04.2 64-bit with GNOME v3.36.8 to be precise), so this is quite a surprise. To doublecheck I cloned the repo into a fresh folder and tried a brand new `npm install` -- which finished without any problems (on both the master and development branches).

But I do remember `fsevents` coming up often in the logs -- so far without any actual problems though, so until now I just didn't care.

Can you provide any more details? I don't know what exactly might be helpful though, so can't ask for anything specific.

**Comment by christophfriedrich** [comment]
Oh hang on, I've got an idea: I'm still on npm v6 -- is the server on v7? Maybe they recently changed how conflicts like this are handled and this breaks it on the server but not on my machine.

**Comment by m-mohr** [comment]
I have quite a number of issues right now on the university VM, so maybe I start with dependencies from scratch and see how that goes...

**Comment by m-mohr** [comment]
VM is running:
npm v12.1
node v10.19.0 (I need to update this)
Ubuntu 20.04.2 LTS

**Comment by christophfriedrich** [comment]
npm v12??? [The most recent one is 7.20.1](https://github.com/npm/cli/releases) :monocle_face: Is that what `npm -v` says?

**Comment by m-mohr** [comment]
lol, forgot to copy the 7 at the beginning - 7.12.1

node will be on 16.x (latest) in a minute.

**Comment by m-mohr** [comment]
npm install succeeds now from a fresh install, I guess that was a npm dependency issue again.
