### ISSUE TITLE
Supported functionality: Partially supported

### ISSUE THREAD

**Issue by m-mohr** [Open-EO/openeo-hub#9]
The "Supported functionality" area currently has groups of functionalities and either reports supported (✔️) or not supported (❌). I just had the idea that we could also report 'partially supported' if any of the endpoints in the group is supported. Not sure about the UI, but a potential Unicode symbol could be ⚠️.

**Comment by aljacob** [comment]
Great idea!

**Comment by m-mohr** [comment]
See also: https://github.com/Open-EO/openeo-vue-components/blob/master/src/components/SupportedFeatures.vue

**Comment by christophfriedrich** [comment]
The Hub now imports the `SupportedFeature` component Matthias mentioned and thus supports this feature too! :-)
